# Generated by Django 3.0.3 on 2020-03-05 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('informationdevice', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCategory',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '问题类别',
                'verbose_name_plural': '问题类别',
                'db_table': 'hisx_ProblemCategorys',
            },
        ),
        migrations.CreateModel(
            name='ProcessedRecord',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('situation', models.TextField()),
                ('solution', models.TextField()),
                ('processing_mode', models.IntegerField(default=1)),
                ('problem_state', models.IntegerField(default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Department')),
                ('discoverer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoverer', to='account.User')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handler', to='account.User')),
                ('problem_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oapm.ProblemCategory')),
            ],
            options={
                'verbose_name': '处理记录',
                'verbose_name_plural': '处理记录',
                'db_table': 'hisx_ProcessedRecs',
            },
        ),
        migrations.CreateModel(
            name='PrinterRepair',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateField(verbose_name='处理日期')),
                ('status', models.BooleanField(default=False)),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User', verbose_name='处理人员')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informationdevice.DeviceInfo', verbose_name='打印机型号')),
            ],
            options={
                'verbose_name': '打印机维修',
                'verbose_name_plural': '打印机维修',
                'db_table': 'hisx_Printerrepairs',
            },
        ),
        migrations.CreateModel(
            name='Cartriday',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateField(verbose_name='加粉日期')),
                ('nums', models.IntegerField(verbose_name='数量')),
                ('status', models.BooleanField(default=False)),
                ('_handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User', verbose_name='处理人员')),
            ],
            options={
                'verbose_name': '硒鼓加粉',
                'verbose_name_plural': '硒鼓加粉',
                'db_table': 'hisx_Cartridays',
            },
        ),
        migrations.CreateModel(
            name='ApplicationSoftWare',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('framework', models.IntegerField(default=1)),
                ('database', models.IntegerField(default=1)),
                ('deployment', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informationdevice.DeviceInfo', verbose_name='安装设备')),
            ],
            options={
                'verbose_name': '应用软件',
                'verbose_name_plural': '应用软件',
                'db_table': 'hisx_ApplicationSoftWare',
            },
        ),
    ]
