const reqCascaderDepartments={
    "status":"0",
    "data":[{
        "value":"1",
        "label":"level1",
        "code":"l",
        "parentvalue":"0",
        "create_time":"2020-01-30",
        "children":[{
            "value":"11",
            "label":"level11",
            "parentvalue":"1",
            "create_time":"2020-01-30",
            "code":"l1"
        },{
            "value":"12",
            "label":"level12",
            "parentvalue":"1",
            "create_time":"2020-01-30",
            "code":"12"
        }]
    },{
        "value":"2",
        "label":"level2",
        "code":"2",
        "parentvalue":"0",
        "create_time":"2020-01-30",
        "children":[{
            "value":"21",
            "label":"level21",
            "parentvalue":"2",
            "create_time":"2020-01-30",
            "code":"21",
            "children":[{
                "value":"211",
                "label":"level211",
                "parentvalue":"21",
                "create_time":"2020-01-30",
                "code":"2l1"
            }]
        },{
            "value":"22",
            "label":"level22",
            "parentvalue":"2",
            "create_time":"2020-01-30",
            "code":"22"
        }]
    },{
        "value":"3",
        "label":"level3",
        "parentvalue":"0",
        "create_time":"2020-01-30",
        "code":"3"
    }]
}

export default reqCascaderDepartments