const reqDeviceInfos={
    "status":"0",
    "data":[{
        "pics":["1","2"],
        "_id":"1",
        "name":"",
        "sn":"",
        "departmentId":"211",
        "devicemodelId":"2",
        "installlocationId":"2",
        "parentID":"",
        "ip":["1","2"],
        "mac":["1","2"],
        "status":"1",
        "os":"0",
        "use":["1","2"],
        "service":["1","2"],
        "os":"0",
        "create_time":"2020-02-20"
        
    },{
        "pics":["3","4"],
        "_id":"2",
        "departmentId":"11",
        "discoverer":"2",
        "problem_category":"1",
        "situation":"无法登陆工号",
        "solution":"重启体检服务器",
        "processing_mode":"2",
        "handler":"1",
        "problem_state":"1",
        "create_time":"2020-01-30"
               
    },{
        "_id":"3",
        "departmentId":"12",
        "discoverer":"2",
        "problem_category":"3",
        "situation":"打印不清晰",
        "solution":"更换色带",
        "processing_mode":"1",
        "handler":"1",
        "problem_state":"2",
        "create_time":"2020-01-30"
    },{
        "_id":"4",
        "departmentId":"22",
        "discoverer":"2",
        "problem_category":"3",
        "situation":"打印不清晰",
        "solution":"更换色带",
        "processing_mode":"1",
        "handler":"1",
        "problem_state":"1",
        "create_time":"2020-01-30"
    },{
        "_id":"5",
        "departmentId":"13",
        "discoverer":"2",
        "problem_category":"3",
        "situation":"打印不清晰",
        "solution":"更换色带",
        "processing_mode":"1",
        "handler":"1",
        "problem_state":"0",
        "create_time":"2020-01-30"
    },{
        "_id":"6",
        "departmentId":"11",
        "discoverer":"2",
        "problem_category":"3",
        "situation":"打印不清晰",
        "solution":"更换色带",
        "processing_mode":"1",
        "handler":"1",
        "problem_state":"1",
        "create_time":"2020-01-30"
    }]
}

export default reqDeviceInfos