const reqProcessedRecords={
    "status":"0",
    "data":[{
        "pics":["1","2"],
        "_id":"1",
        "departmentId":"211",
        "discoverer":"2",
        "problem_category":"2",
        "situation":"工作需求，新安装电脑打印机，需重新布线",
        "solution":"根据需求安装",
        "processing_mode":"1",
        "handler":"1",
        "problem_state":"0",
        "create_time":"2020-02-20"
        
    },{
        "pics":["3","4"],
        "_id":"2",
        "departmentId":"11",
        "discoverer":"2",
        "problem_category":"1",
        "situation":"无法登陆工号",
        "solution":"重启体检服务器",
        "processing_mode":"2",
        "handler":"1",
        "problem_state":"1",
        "create_time":"2020-01-30"
               
    },{
        "_id":"3",
        "departmentId":"12",
        "discoverer":"2",
        "problem_category":"3",
        "situation":"打印不清晰",
        "solution":"更换色带",
        "processing_mode":"1",
        "handler":"1",
        "problem_state":"2",
        "create_time":"2020-01-30"
    },{
        "_id":"4",
        "departmentId":"22",
        "discoverer":"2",
        "problem_category":"3",
        "situation":"打印不清晰",
        "solution":"更换色带",
        "processing_mode":"1",
        "handler":"1",
        "problem_state":"1",
        "create_time":"2020-01-30"
    },{
        "_id":"5",
        "departmentId":"13",
        "discoverer":"2",
        "problem_category":"3",
        "situation":"打印不清晰",
        "solution":"更换色带",
        "processing_mode":"1",
        "handler":"1",
        "problem_state":"0",
        "create_time":"2020-01-30"
    },{
        "_id":"6",
        "departmentId":"11",
        "discoverer":"2",
        "problem_category":"3",
        "situation":"打印不清晰",
        "solution":"更换色带",
        "processing_mode":"1",
        "handler":"1",
        "problem_state":"1",
        "create_time":"2020-01-30"
    }]
}

export default reqProcessedRecords