# Generated by Django 3.0.3 on 2020-06-11 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateField(verbose_name='入库日期')),
                ('name', models.CharField(max_length=50)),
                ('isbn', models.TextField(blank=True, null=True)),
                ('cover', models.TextField(blank=True, null=True)),
                ('profile', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'Books',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '图书类别',
                'verbose_name_plural': '图书类别',
                'db_table': 'hisx_BookCategorys',
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(verbose_name='借出日期')),
                ('return_time', models.DateTimeField(verbose_name='归还日期')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='bms.Book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader', to='account.User')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'db_table': 'hisx_BorrowRecords',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='bookcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.BookCategory'),
        ),
    ]
