# Generated by Django 3.0.3 on 2020-06-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_time',
            field=models.DateTimeField(verbose_name='入库日期'),
        ),
    ]
