# Generated by Django 3.0.3 on 2020-06-14 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0002_auto_20200612_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisheryear',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建日期'),
        ),
        migrations.AlterModelTable(
            name='book',
            table='hisx_Books',
        ),
        migrations.CreateModel(
            name='BookStock',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(verbose_name='入库日期')),
                ('nums', models.IntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.Book')),
            ],
            options={
                'verbose_name': '图书库存',
                'verbose_name_plural': '图书库存',
                'db_table': 'hisx_BookStocks',
            },
        ),
    ]
