# Generated by Django 3.0.3 on 2020-06-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0004_remove_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
