# Generated by Django 3.0.3 on 2020-06-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0005_book_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='stock',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
