# Generated by Django 3.0.3 on 2020-04-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='create_time',
            field=models.DateTimeField(verbose_name='记录日期'),
        ),
    ]
