hisconn="zlhis/z2ohis@192.168.100.120:1521/orcl"
hqmsbydata='''select a.病人id, a.主页id, 0 as 状态,
       (select 参数值 from hqms对接参数 where 参数名 = '机构编码') as A01,
       (select 参数值 from hqms对接参数 where 参数名 = '机构名称') as A02,
       a.病案号 as A48,
       a.主页id as A49,
       To_Char(a.入院日期, 'yyyy-MM-dd HH24:mm:ss') as B12,
       To_Char(a.出院日期, 'yyyy-MM-dd HH24:mm:ss') as B15,
       '-' as A47,
       zl_fun_hqms编码对应('RC032', null, a.医疗付款方式) as A46C,
       substrb(a.姓名, 1, 40) as A11,
       Decode(a.性别, '男', 1, '女', '2', '未知', 0, 9) as A12C,
       To_Char(b.出生日期, 'yyyy-MM-dd') as A13,
       zl_fun_hqms_Age(a.病人id, a.主页id, a.年龄, 1) as A14,
       b.国籍 as A15C,
       zl_fun_hqms编码对应('RC002', null, a.婚姻状况) as A21C,
       zl_fun_hqms编码对应('RC003', null, a.职业) as A38C,
       zl_fun_hqms编码对应('RC035', null, b.民族) as A19C,
       Nvl(b.身份证号, '-') as A20,
         DECODE(b.出生地点,'','贵州省六盘水市钟山区',b.出生地点)  as A22,
       Nvl(zl_fun_hqms_城市(a.病人id, a.主页id, a.家庭地址), '23') as A23C,
        DECODE( a.户口地址,'','贵州省六盘水市钟山区', a.户口地址)   as A24,
       DECODE(a.户口地址邮编,'','553000',a.户口地址邮编)  as A25C,
       a.家庭地址 as A26,
         DECODE(a.家庭电话,'','-',a.家庭电话) as A27,
        DECODE(a.家庭地址邮编,'','553000',a.家庭地址邮编) as A28C,
       a.单位地址 as A29,
       DECODE(a.单位电话,'','-',a.单位电话) as A30,
       DECODE(a.单位邮编,'','-',a.单位邮编) as A31C,
     DECODE(a.联系人姓名,'',substrb(a.姓名, 1, 40),substrb(a.联系人姓名, 1, 40)) as A32,
       zl_fun_hqms编码对应('RC033', null, a.联系人关系) as A33C,
       DECODE(a.联系人地址,'','-',a.联系人地址) as A34,
      DECODE(a.联系人电话,'','-',a.联系人电话) as A35,
       zl_fun_hqms编码对应('RC026', null, a.入院方式) as B11C,
       zl_fun_hqms编码对应('RC023', a.入院科室id) as B13C,
       NVL(a.入院病床,'-' ) as B14,
       (select To_Char(wmsys.wm_concat(zl_fun_hqms编码对应('RC023', 科室id)))
           from 病人变动记录
          where 病人id = a.病人id and 主页id = a.主页id and 开始原因 = 3) as B21C,
       zl_fun_hqms编码对应('RC023', a.出院科室id) as B16C,
       decode(a.出院病床,'','-',a.出院病床) as B17,
       a.住院天数 as B20,
       zl_fun_hqms诊断(a.病人id, a.主页id, 1, 1, 1) as C01C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 1, 1, 2) as C02N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 1, 1) as C03C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 1, 2) as C04N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 1, 3) as C05C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 2, 1) as C06x01C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 2, 2) as C07x01N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 2, 3) as C08x01C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 3, 1) as C06x02C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 3, 2) as C07x02N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 3, 3) as C08x02C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 4, 1) as C06x03C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 4, 2) as C07x03N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 4, 3) as C08x03C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 5, 1) as C06x04C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 5, 2) as C07x04N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 5, 3) as C08x04C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 6, 1) as C06x05C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 6, 2) as C07x05N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 6, 3) as C08x05C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 7, 1) as C06x06C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 7, 2) as C07x06N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 7, 3) as C08x06C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 8, 1) as C06x07C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 8, 2) as C07x07N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 8, 3) as C08x07C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 9, 1) as C06x08C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 9, 2) as C07x08N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 9, 3) as C08x08C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 10, 1) as C06x09C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 10, 2) as C07x09N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 10, 3) as C08x09C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 11, 1) as C06x10C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 11, 2) as C07x10N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 11, 3) as C08x10C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 6, 1, 1) as C09C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 6, 1, 2) as C10N,
       Nvl(zl_fun_病案主页从表(a.病人id, a.主页id, '病理号'), '-') as C11,
       zl_fun_hqms诊断(a.病人id, a.主页id, 7, 1, 1) as C12C,   
       zl_fun_hqms诊断(a.病人id, a.主页id, 7, 1, 2) as C13N,
       (select Decode(Count(1), 0, 1, 2)
           from 病人过敏记录
          where 病人id = a.病人id and 主页id = a.主页id and nvl(结果, 0) = 1 and
                药物名 is not null) as C24C,
       (select To_Char(wmsys.wm_concat(distinct 药物名))
           from 病人过敏记录
          where 病人id = a.病人id and 主页id = a.主页id and nvl(结果, 0) = 1 and
                药物名 is not null) as C25,
      Nvl(zl_fun_病案主页从表(a.病人id, a.主页id, '科主任'), '郭炯辉') as B22,
      Nvl(zl_fun_病案主页从表(a.病人id, a.主页id, '主任医师'), '郭炯辉')   as B23,
       Nvl(zl_fun_病案主页从表(a.病人id, a.主页id, '主治医师'), '郭炯辉')  as B24,
       a.住院医师 as B25,
       Nvl(a.责任护士, '李美星')   as B26,
       zl_fun_病案主页从表(a.病人id, a.主页id, '进修医师') as B27,
       zl_fun_病案主页从表(a.病人id, a.主页id, '实习医师') as B28,
       a.编目员姓名 as B29,
       decode(zl_fun_病案主页从表(a.病人id, a.主页id, '病案质量'), '甲', 1,
               '乙', 2, '丙', 3, 1) as B30C,
       zl_fun_病案主页从表(a.病人id, a.主页id, '质控医师') as B31,
       zl_fun_病案主页从表(a.病人id, a.主页id, '质控护士') as B32,
       zl_fun_病案主页从表(a.病人id, a.主页id, '主页质量日期') as B33,
       Decode(a.尸检标志, 1, 1, 2) as C34C,
       decode(a.血型, 'A型', 1, 'B型', 2, 'O型', 3, 'AB型', 4, '不详', 5,
               '未查', 6, 5) as C26C,
       decode(zl_fun_病案主页从表(a.病人id, a.主页id, 'RH'), '阴', 1, '阳',
               2, '不详', 3, '未查', 4, 3) as C27C,
       NVL(zl_fun_hqms手术(a.病人id, a.主页id, 1, 1),'-') as C14x01C,
       nvl(zl_fun_hqms手术(a.病人id, a.主页id, 1, 2),'-') as C15x01N,
       nvl(zl_fun_hqms手术(a.病人id, a.主页id, 1, 3),'-') as C16x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 4) as C17x01,
       
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 5) as C18x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 6) as C19x01,
     
       Nvl( zl_fun_hqms手术(a.病人id, a.主页id, 1, 7), zl_fun_hqms手术(a.病人id, a.主页id, 1, 6))  as C20x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 8) as C21x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 9) as C22x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 10) as C23x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 1) as C35x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 2) as C36x01N,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 3) as C37x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 4) as C38x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 5) as C39x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 6) as C40x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 7) as C41x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 8) as C42x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 9) as C43x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 10) as C44x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 1) as C35x02C,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 2) as C36x02N,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 3) as C37x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 4) as C38x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 5) as C39x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 6) as C40x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 7) as C41x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 8) as C42x02C,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 9) as C43x02C,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 10) as C44x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 1) as C35x03C,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 2) as C36x03N,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 3) as C37x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 4) as C38x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 5) as C39x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 6) as C40x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 7) as C41x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 8) as C42x03C,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 9) as C43x03C,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 10) as C44x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 1) as C35x04C,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 2) as C36x04N,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 3) as C37x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 4) as C38x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 5) as C39x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 6) as C40x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 7) as C41x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 8) as C42x04C,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 9) as C43x04C,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 10) as C44x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 1) as C35x05C,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 2) as C36x05N,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 3) as C37x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 4) as C38x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 5) as C39x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 6) as C40x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 7) as C41x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 8) as C42x05C,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 9) as C43x05C,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 10) as C44x05,
      decode(zl_fun_hqms_Age(a.病人id, a.主页id, a.年龄, 2),'0','',zl_fun_hqms_Age(a.病人id, a.主页id, a.年龄, 2)) as A16,
       zl_fun_病案主页从表(a.病人id, a.主页id, '新生儿出生体重') as A18x01,
       Null as A18x02,
       Null as A18x03,
       Null as A18x04,
       Null as A18x05,
       zl_fun_病案主页从表(a.病人id, a.主页id, '新生儿入院体重') as A17,
        nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)), 1,instr(max(decode(信息名, '昏迷时间', 信息值)), ',') - 1) as 昏迷时间
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C28,
        nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',') + 1,
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               instr(max(decode(信息名, '昏迷时间', 信息值)), ',') + 1) -
                         instr(max(decode(信息名, '昏迷时间', 信息值)), ',') - 1)
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C29,
       nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               instr(max(decode(信息名, '昏迷时间', 信息值)), ',') + 1) + 1,
                        instr(max(decode(信息名, '昏迷时间', 信息值)), '|') -
                         (instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                                instr(max(decode(信息名, '昏迷时间', 信息值)), ',') + 1) + 1))
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C30,
       nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), '|') + 1,
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               (instr(max(decode(信息名, '昏迷时间', 信息值)), '|')) + 1) -
                         instr(max(decode(信息名, '昏迷时间', 信息值)), '|') - 1)
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C31,
       nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               (instr(max(decode(信息名, '昏迷时间', 信息值)), '|')) + 1) + 1,
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                                      (instr(max(decode(信息名, '昏迷时间', 信息值)),
                                              '|')) + 1) + 1) -
                         instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               (instr(max(decode(信息名, '昏迷时间', 信息值)), '|')) + 1) - 1)
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C32,
       nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                                      (instr(max(decode(信息名, '昏迷时间', 信息值)),
                                              '|')) + 1) + 1) + 1)
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C33,
       Decode(zl_fun_病案主页从表(a.病人id, a.主页id, '31天内再住院'), Null,
               1, '', 1, 2) as B36C,
       zl_fun_病案主页从表(a.病人id, a.主页id, '31天内再住院') as B37,
       decode(a.出院方式, '医嘱离院', 1, '转院', 2, '转社区', 3, '正常', 1,
               '自动出院', 1, '其他', 9, '非医嘱离院', 4, '死亡', 5,
               '回常驻地', 9, 9) as B34C,
       zl_fun_病案主页从表(a.病人id, a.主页id, '出院转入') as B35,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D01') as D01,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D09') as D09,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D11') as D11,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D12') as D12,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D13') as D13,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D14') as D14,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D15') as D15,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D16') as D16,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D17') as D17,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D18') as D18,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D19') as D19,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D19x01') as D19x01,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D20') as D20,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D20x01') as D20x01,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D20x02') as D20x02,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D21') as D21,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D22') as D22,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D23') as D23,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D23x01') as D23x01,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D24') as D24,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D25') as D25,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D26') as D26,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D27') as D27,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D28') as D28,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D29') as D29,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D30') as D30,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D31') as D31,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D32') as D32,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D33') as D33,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D34') as D34
      , sysdate as 记录日期, user as 记录人, null as 说明, a.编目日期,
       a.出院日期
  from 病案主页 a, 病人信息 b
 where a.病人id = b.病人id and 
       a.病案号 is not  null and  zl_fun_hqms费用(a.病人id, a.主页id, 'D01')<>0 and 
       a.出院日期 between TO_DATE(:1,'YYYY-MM-DD HH24:MI:SS') and TO_DATE(:2,'YYYY-MM-DD HH24:MI:SS')
union all
select a.病人id, a.主页id, 0 as 状态,
       (select 参数值 from hqms对接参数 where 参数名 = '机构编码') as A01,
       (select 参数值 from hqms对接参数 where 参数名 = '机构名称') as A02,
       a.病案号 as A48,
       a.主页id as A49,
       To_Char(a.入院日期, 'yyyy-MM-dd HH24:mm:ss') as B12,
       To_Char(a.出院日期, 'yyyy-MM-dd HH24:mm:ss') as B15,
       '-' as A47,
       zl_fun_hqms编码对应('RC032', null, a.医疗付款方式) as A46C,
       substrb(a.姓名, 1, 40) as A11,
       Decode(a.性别, '男', 1, '女', '2', '未知', 0, 9) as A12C,
       To_Char(b.出生日期, 'yyyy-MM-dd') as A13,
       zl_fun_hqms_Age(a.病人id, a.主页id, a.年龄, 1) as A14,
       b.国籍 as A15C,
       zl_fun_hqms编码对应('RC002', null, a.婚姻状况) as A21C,
       zl_fun_hqms编码对应('RC003', null, a.职业) as A38C,
       zl_fun_hqms编码对应('RC035', null, b.民族) as A19C,
       Nvl(b.身份证号, '-') as A20,
         DECODE(b.出生地点,'','贵州省六盘水市钟山区',b.出生地点)  as A22,
       Nvl(zl_fun_hqms_城市(a.病人id, a.主页id, a.家庭地址), '23') as A23C,
        DECODE( a.户口地址,'','贵州省六盘水市钟山区', a.户口地址)   as A24,
       DECODE(a.户口地址邮编,'','553000',a.户口地址邮编)  as A25C,
       a.家庭地址 as A26,
         DECODE(a.家庭电话,'','-',a.家庭电话) as A27,
        DECODE(a.家庭地址邮编,'','553000',a.家庭地址邮编) as A28C,
       a.单位地址 as A29,
       DECODE(a.单位电话,'','-',a.单位电话) as A30,
       DECODE(a.单位邮编,'','-',a.单位邮编) as A31C,
     DECODE(a.联系人姓名,'',substrb(a.姓名, 1, 40),substrb(a.联系人姓名, 1, 40)) as A32,
       zl_fun_hqms编码对应('RC033', null, a.联系人关系) as A33C,
       DECODE(a.联系人地址,'','-',a.联系人地址) as A34,
      DECODE(a.联系人电话,'','-',a.联系人电话) as A35,
       zl_fun_hqms编码对应('RC026', null, a.入院方式) as B11C,
       zl_fun_hqms编码对应('RC023', a.入院科室id) as B13C,
       NVL(a.入院病床,'-' ) as B14,
       (select To_Char(wmsys.wm_concat(zl_fun_hqms编码对应('RC023', 科室id)))
           from 病人变动记录
          where 病人id = a.病人id and 主页id = a.主页id and 开始原因 = 3) as B21C,
       zl_fun_hqms编码对应('RC023', a.出院科室id) as B16C,
       decode(a.出院病床,'','-',a.出院病床) as B17,
       a.住院天数 as B20,
       zl_fun_hqms诊断(a.病人id, a.主页id, 1, 1, 1) as C01C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 1, 1, 2) as C02N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 1, 1) as C03C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 1, 2) as C04N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 1, 3) as C05C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 2, 1) as C06x01C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 2, 2) as C07x01N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 2, 3) as C08x01C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 3, 1) as C06x02C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 3, 2) as C07x02N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 3, 3) as C08x02C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 4, 1) as C06x03C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 4, 2) as C07x03N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 4, 3) as C08x03C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 5, 1) as C06x04C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 5, 2) as C07x04N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 5, 3) as C08x04C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 6, 1) as C06x05C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 6, 2) as C07x05N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 6, 3) as C08x05C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 7, 1) as C06x06C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 7, 2) as C07x06N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 7, 3) as C08x06C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 8, 1) as C06x07C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 8, 2) as C07x07N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 8, 3) as C08x07C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 9, 1) as C06x08C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 9, 2) as C07x08N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 9, 3) as C08x08C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 10, 1) as C06x09C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 10, 2) as C07x09N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 10, 3) as C08x09C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 11, 1) as C06x10C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 11, 2) as C07x10N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 11, 3) as C08x10C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 6, 1, 1) as C09C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 6, 1, 2) as C10N,
       Nvl(zl_fun_病案主页从表(a.病人id, a.主页id, '病理号'), '-') as C11,
       zl_fun_hqms诊断(a.病人id, a.主页id, 7, 1, 1) as C12C,   
       zl_fun_hqms诊断(a.病人id, a.主页id, 7, 1, 2) as C13N,
       (select Decode(Count(1), 0, 1, 2)
           from 病人过敏记录
          where 病人id = a.病人id and 主页id = a.主页id and nvl(结果, 0) = 1 and
                药物名 is not null) as C24C,
       (select To_Char(wmsys.wm_concat(distinct 药物名))
           from 病人过敏记录
          where 病人id = a.病人id and 主页id = a.主页id and nvl(结果, 0) = 1 and
                药物名 is not null) as C25,
      Nvl(zl_fun_病案主页从表(a.病人id, a.主页id, '科主任'), '郭炯辉') as B22,
      Nvl(zl_fun_病案主页从表(a.病人id, a.主页id, '主任医师'), '郭炯辉')   as B23,
       Nvl(zl_fun_病案主页从表(a.病人id, a.主页id, '主治医师'), '郭炯辉')  as B24,
       a.住院医师 as B25,
       Nvl(a.责任护士, '李美星')   as B26,
       zl_fun_病案主页从表(a.病人id, a.主页id, '进修医师') as B27,
       zl_fun_病案主页从表(a.病人id, a.主页id, '实习医师') as B28,
       a.编目员姓名 as B29,
       decode(zl_fun_病案主页从表(a.病人id, a.主页id, '病案质量'), '甲', 1,
               '乙', 2, '丙', 3, 1) as B30C,
       zl_fun_病案主页从表(a.病人id, a.主页id, '质控医师') as B31,
       zl_fun_病案主页从表(a.病人id, a.主页id, '质控护士') as B32,
       zl_fun_病案主页从表(a.病人id, a.主页id, '主页质量日期') as B33,
       Decode(a.尸检标志, 1, 1, 2) as C34C,
       decode(a.血型, 'A型', 1, 'B型', 2, 'O型', 3, 'AB型', 4, '不详', 5,
               '未查', 6, 5) as C26C,
       decode(zl_fun_病案主页从表(a.病人id, a.主页id, 'RH'), '阴', 1, '阳',
               2, '不详', 3, '未查', 4, 3) as C27C,
       NVL(zl_fun_hqms手术(a.病人id, a.主页id, 1, 1),'-') as C14x01C,
       nvl(zl_fun_hqms手术(a.病人id, a.主页id, 1, 2),'-') as C15x01N,
       nvl(zl_fun_hqms手术(a.病人id, a.主页id, 1, 3),'-') as C16x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 4) as C17x01,
       
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 5) as C18x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 6) as C19x01,
     
       Nvl( zl_fun_hqms手术(a.病人id, a.主页id, 1, 7), zl_fun_hqms手术(a.病人id, a.主页id, 1, 6))  as C20x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 8) as C21x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 9) as C22x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 10) as C23x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 1) as C35x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 2) as C36x01N,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 3) as C37x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 4) as C38x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 5) as C39x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 6) as C40x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 7) as C41x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 8) as C42x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 9) as C43x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 10) as C44x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 1) as C35x02C,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 2) as C36x02N,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 3) as C37x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 4) as C38x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 5) as C39x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 6) as C40x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 7) as C41x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 8) as C42x02C,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 9) as C43x02C,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 10) as C44x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 1) as C35x03C,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 2) as C36x03N,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 3) as C37x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 4) as C38x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 5) as C39x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 6) as C40x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 7) as C41x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 8) as C42x03C,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 9) as C43x03C,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 10) as C44x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 1) as C35x04C,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 2) as C36x04N,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 3) as C37x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 4) as C38x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 5) as C39x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 6) as C40x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 7) as C41x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 8) as C42x04C,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 9) as C43x04C,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 10) as C44x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 1) as C35x05C,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 2) as C36x05N,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 3) as C37x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 4) as C38x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 5) as C39x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 6) as C40x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 7) as C41x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 8) as C42x05C,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 9) as C43x05C,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 10) as C44x05,
      decode(zl_fun_hqms_Age(a.病人id, a.主页id, a.年龄, 2),'0','',zl_fun_hqms_Age(a.病人id, a.主页id, a.年龄, 2)) as A16,
       zl_fun_病案主页从表(a.病人id, a.主页id, '新生儿出生体重') as A18x01,
       Null as A18x02,
       Null as A18x03,
       Null as A18x04,
       Null as A18x05,
       zl_fun_病案主页从表(a.病人id, a.主页id, '新生儿入院体重') as A17,
        nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)), 1,instr(max(decode(信息名, '昏迷时间', 信息值)), ',') - 1) as 昏迷时间
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C28,
        nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',') + 1,
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               instr(max(decode(信息名, '昏迷时间', 信息值)), ',') + 1) -
                         instr(max(decode(信息名, '昏迷时间', 信息值)), ',') - 1)
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C29,
       nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               instr(max(decode(信息名, '昏迷时间', 信息值)), ',') + 1) + 1,
                        instr(max(decode(信息名, '昏迷时间', 信息值)), '|') -
                         (instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                                instr(max(decode(信息名, '昏迷时间', 信息值)), ',') + 1) + 1))
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C30,
       nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), '|') + 1,
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               (instr(max(decode(信息名, '昏迷时间', 信息值)), '|')) + 1) -
                         instr(max(decode(信息名, '昏迷时间', 信息值)), '|') - 1)
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C31,
       nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               (instr(max(decode(信息名, '昏迷时间', 信息值)), '|')) + 1) + 1,
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                                      (instr(max(decode(信息名, '昏迷时间', 信息值)),
                                              '|')) + 1) + 1) -
                         instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               (instr(max(decode(信息名, '昏迷时间', 信息值)), '|')) + 1) - 1)
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C32,
       nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                                      (instr(max(decode(信息名, '昏迷时间', 信息值)),
                                              '|')) + 1) + 1) + 1)
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C33,
       Decode(zl_fun_病案主页从表(a.病人id, a.主页id, '31天内再住院'), Null,
               1, '', 1, 2) as B36C,
       zl_fun_病案主页从表(a.病人id, a.主页id, '31天内再住院') as B37,
       decode(a.出院方式, '医嘱离院', 1, '转院', 2, '转社区', 3, '正常', 1,
               '自动出院', 1, '其他', 9, '非医嘱离院', 4, '死亡', 5,
               '回常驻地', 9, 9) as B34C,
       zl_fun_病案主页从表(a.病人id, a.主页id, '出院转入') as B35,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D01') as D01,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D09') as D09,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D11') as D11,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D12') as D12,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D13') as D13,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D14') as D14,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D15') as D15,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D16') as D16,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D17') as D17,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D18') as D18,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D19') as D19,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D19x01') as D19x01,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D20') as D20,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D20x01') as D20x01,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D20x02') as D20x02,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D21') as D21,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D22') as D22,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D23') as D23,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D23x01') as D23x01,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D24') as D24,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D25') as D25,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D26') as D26,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D27') as D27,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D28') as D28,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D29') as D29,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D30') as D30,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D31') as D31,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D32') as D32,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D33') as D33,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D34') as D34
      , sysdate as 记录日期, user as 记录人, null as 说明, a.编目日期,
       a.出院日期
  from 病案主页 a, 病人信息 b
 where a.病人id = b.病人id and 
       a.病案号 is not  null and 
       a.出院日期 between TO_DATE(:3,'YYYY-MM-DD HH24:MI:SS') and TO_DATE(:4,'YYYY-MM-DD HH24:MI:SS')
       AND zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D01')<>0'''
       
hqmsbypnum='''select a.病人id, a.主页id, 0 as 状态,
       (select 参数值 from hqms对接参数 where 参数名 = '机构编码') as A01,
       (select 参数值 from hqms对接参数 where 参数名 = '机构名称') as A02,
       a.病案号 as A48,
       a.主页id as A49,
       To_Char(a.入院日期, 'yyyy-MM-dd HH24:mm:ss') as B12,
       To_Char(a.出院日期, 'yyyy-MM-dd HH24:mm:ss') as B15,
       '-' as A47,
       zl_fun_hqms编码对应('RC032', null, a.医疗付款方式) as A46C,
       substrb(a.姓名, 1, 40) as A11,
       Decode(a.性别, '男', 1, '女', '2', '未知', 0, 9) as A12C,
       To_Char(b.出生日期, 'yyyy-MM-dd') as A13,
       zl_fun_hqms_Age(a.病人id, a.主页id, a.年龄, 1) as A14,
       b.国籍 as A15C,
       zl_fun_hqms编码对应('RC002', null, a.婚姻状况) as A21C,
       zl_fun_hqms编码对应('RC003', null, a.职业) as A38C,
       zl_fun_hqms编码对应('RC035', null, b.民族) as A19C,
       Nvl(b.身份证号, '-') as A20,
         DECODE(b.出生地点,'','贵州省六盘水市钟山区',b.出生地点)  as A22,
       Nvl(zl_fun_hqms_城市(a.病人id, a.主页id, a.家庭地址), '23') as A23C,
        DECODE( a.户口地址,'','贵州省六盘水市钟山区', a.户口地址)   as A24,
       DECODE(a.户口地址邮编,'','553000',a.户口地址邮编)  as A25C,
       a.家庭地址 as A26,
         DECODE(a.家庭电话,'','-',a.家庭电话) as A27,
        DECODE(a.家庭地址邮编,'','553000',a.家庭地址邮编) as A28C,
       a.单位地址 as A29,
       DECODE(a.单位电话,'','-',a.单位电话) as A30,
       DECODE(a.单位邮编,'','-',a.单位邮编) as A31C,
     DECODE(a.联系人姓名,'',substrb(a.姓名, 1, 40),substrb(a.联系人姓名, 1, 40)) as A32,
       zl_fun_hqms编码对应('RC033', null, a.联系人关系) as A33C,
       DECODE(a.联系人地址,'','-',a.联系人地址) as A34,
      DECODE(a.联系人电话,'','-',a.联系人电话) as A35,
       zl_fun_hqms编码对应('RC026', null, a.入院方式) as B11C,
       zl_fun_hqms编码对应('RC023', a.入院科室id) as B13C,
       NVL(a.入院病床,'-' ) as B14,
       (select To_Char(wmsys.wm_concat(zl_fun_hqms编码对应('RC023', 科室id)))
           from 病人变动记录
          where 病人id = a.病人id and 主页id = a.主页id and 开始原因 = 3) as B21C,
       zl_fun_hqms编码对应('RC023', a.出院科室id) as B16C,
       decode(a.出院病床,'','-',a.出院病床) as B17,
       a.住院天数 as B20,
       zl_fun_hqms诊断(a.病人id, a.主页id, 1, 1, 1) as C01C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 1, 1, 2) as C02N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 1, 1) as C03C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 1, 2) as C04N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 1, 3) as C05C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 2, 1) as C06x01C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 2, 2) as C07x01N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 2, 3) as C08x01C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 3, 1) as C06x02C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 3, 2) as C07x02N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 3, 3) as C08x02C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 4, 1) as C06x03C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 4, 2) as C07x03N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 4, 3) as C08x03C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 5, 1) as C06x04C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 5, 2) as C07x04N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 5, 3) as C08x04C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 6, 1) as C06x05C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 6, 2) as C07x05N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 6, 3) as C08x05C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 7, 1) as C06x06C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 7, 2) as C07x06N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 7, 3) as C08x06C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 8, 1) as C06x07C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 8, 2) as C07x07N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 8, 3) as C08x07C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 9, 1) as C06x08C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 9, 2) as C07x08N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 9, 3) as C08x08C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 10, 1) as C06x09C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 10, 2) as C07x09N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 10, 3) as C08x09C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 11, 1) as C06x10C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 11, 2) as C07x10N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 11, 3) as C08x10C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 6, 1, 1) as C09C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 6, 1, 2) as C10N,
       Nvl(zl_fun_病案主页从表(a.病人id, a.主页id, '病理号'), '-') as C11,
       zl_fun_hqms诊断(a.病人id, a.主页id, 7, 1, 1) as C12C,   
       zl_fun_hqms诊断(a.病人id, a.主页id, 7, 1, 2) as C13N,
       (select Decode(Count(1), 0, 1, 2)
           from 病人过敏记录
          where 病人id = a.病人id and 主页id = a.主页id and nvl(结果, 0) = 1 and
                药物名 is not null) as C24C,
       (select To_Char(wmsys.wm_concat(distinct 药物名))
           from 病人过敏记录
          where 病人id = a.病人id and 主页id = a.主页id and nvl(结果, 0) = 1 and
                药物名 is not null) as C25,
      Nvl(zl_fun_病案主页从表(a.病人id, a.主页id, '科主任'), '郭炯辉') as B22,
      Nvl(zl_fun_病案主页从表(a.病人id, a.主页id, '主任医师'), '郭炯辉')   as B23,
       Nvl(zl_fun_病案主页从表(a.病人id, a.主页id, '主治医师'), '郭炯辉')  as B24,
       a.住院医师 as B25,
       Nvl(a.责任护士, '李美星')   as B26,
       zl_fun_病案主页从表(a.病人id, a.主页id, '进修医师') as B27,
       zl_fun_病案主页从表(a.病人id, a.主页id, '实习医师') as B28,
       a.编目员姓名 as B29,
       decode(zl_fun_病案主页从表(a.病人id, a.主页id, '病案质量'), '甲', 1,
               '乙', 2, '丙', 3, 1) as B30C,
       zl_fun_病案主页从表(a.病人id, a.主页id, '质控医师') as B31,
       zl_fun_病案主页从表(a.病人id, a.主页id, '质控护士') as B32,
       zl_fun_病案主页从表(a.病人id, a.主页id, '主页质量日期') as B33,
       Decode(a.尸检标志, 1, 1, 2) as C34C,
       decode(a.血型, 'A型', 1, 'B型', 2, 'O型', 3, 'AB型', 4, '不详', 5,
               '未查', 6, 5) as C26C,
       decode(zl_fun_病案主页从表(a.病人id, a.主页id, 'RH'), '阴', 1, '阳',
               2, '不详', 3, '未查', 4, 3) as C27C,
       NVL(zl_fun_hqms手术(a.病人id, a.主页id, 1, 1),'-') as C14x01C,
       nvl(zl_fun_hqms手术(a.病人id, a.主页id, 1, 2),'-') as C15x01N,
       nvl(zl_fun_hqms手术(a.病人id, a.主页id, 1, 3),'-') as C16x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 4) as C17x01,
       
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 5) as C18x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 6) as C19x01,
     
       Nvl( zl_fun_hqms手术(a.病人id, a.主页id, 1, 7), zl_fun_hqms手术(a.病人id, a.主页id, 1, 6))  as C20x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 8) as C21x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 9) as C22x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 10) as C23x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 1) as C35x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 2) as C36x01N,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 3) as C37x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 4) as C38x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 5) as C39x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 6) as C40x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 7) as C41x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 8) as C42x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 9) as C43x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 10) as C44x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 1) as C35x02C,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 2) as C36x02N,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 3) as C37x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 4) as C38x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 5) as C39x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 6) as C40x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 7) as C41x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 8) as C42x02C,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 9) as C43x02C,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 10) as C44x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 1) as C35x03C,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 2) as C36x03N,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 3) as C37x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 4) as C38x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 5) as C39x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 6) as C40x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 7) as C41x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 8) as C42x03C,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 9) as C43x03C,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 10) as C44x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 1) as C35x04C,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 2) as C36x04N,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 3) as C37x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 4) as C38x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 5) as C39x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 6) as C40x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 7) as C41x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 8) as C42x04C,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 9) as C43x04C,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 10) as C44x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 1) as C35x05C,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 2) as C36x05N,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 3) as C37x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 4) as C38x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 5) as C39x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 6) as C40x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 7) as C41x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 8) as C42x05C,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 9) as C43x05C,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 10) as C44x05,
      decode(zl_fun_hqms_Age(a.病人id, a.主页id, a.年龄, 2),'0','',zl_fun_hqms_Age(a.病人id, a.主页id, a.年龄, 2)) as A16,
       zl_fun_病案主页从表(a.病人id, a.主页id, '新生儿出生体重') as A18x01,
       Null as A18x02,
       Null as A18x03,
       Null as A18x04,
       Null as A18x05,
       zl_fun_病案主页从表(a.病人id, a.主页id, '新生儿入院体重') as A17,
        nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)), 1,instr(max(decode(信息名, '昏迷时间', 信息值)), ',') - 1) as 昏迷时间
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C28,
        nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',') + 1,
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               instr(max(decode(信息名, '昏迷时间', 信息值)), ',') + 1) -
                         instr(max(decode(信息名, '昏迷时间', 信息值)), ',') - 1)
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C29,
       nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               instr(max(decode(信息名, '昏迷时间', 信息值)), ',') + 1) + 1,
                        instr(max(decode(信息名, '昏迷时间', 信息值)), '|') -
                         (instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                                instr(max(decode(信息名, '昏迷时间', 信息值)), ',') + 1) + 1))
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C30,
       nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), '|') + 1,
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               (instr(max(decode(信息名, '昏迷时间', 信息值)), '|')) + 1) -
                         instr(max(decode(信息名, '昏迷时间', 信息值)), '|') - 1)
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C31,
       nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               (instr(max(decode(信息名, '昏迷时间', 信息值)), '|')) + 1) + 1,
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                                      (instr(max(decode(信息名, '昏迷时间', 信息值)),
                                              '|')) + 1) + 1) -
                         instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               (instr(max(decode(信息名, '昏迷时间', 信息值)), '|')) + 1) - 1)
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C32,
       nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                                      (instr(max(decode(信息名, '昏迷时间', 信息值)),
                                              '|')) + 1) + 1) + 1)
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C33,
       Decode(zl_fun_病案主页从表(a.病人id, a.主页id, '31天内再住院'), Null,
               1, '', 1, 2) as B36C,
       zl_fun_病案主页从表(a.病人id, a.主页id, '31天内再住院') as B37,
       decode(a.出院方式, '医嘱离院', 1, '转院', 2, '转社区', 3, '正常', 1,
               '自动出院', 1, '其他', 9, '非医嘱离院', 4, '死亡', 5,
               '回常驻地', 9, 9) as B34C,
       zl_fun_病案主页从表(a.病人id, a.主页id, '出院转入') as B35,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D01') as D01,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D09') as D09,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D11') as D11,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D12') as D12,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D13') as D13,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D14') as D14,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D15') as D15,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D16') as D16,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D17') as D17,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D18') as D18,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D19') as D19,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D19x01') as D19x01,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D20') as D20,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D20x01') as D20x01,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D20x02') as D20x02,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D21') as D21,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D22') as D22,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D23') as D23,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D23x01') as D23x01,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D24') as D24,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D25') as D25,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D26') as D26,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D27') as D27,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D28') as D28,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D29') as D29,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D30') as D30,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D31') as D31,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D32') as D32,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D33') as D33,
       zl_fun_hqms费用(a.病人id, a.主页id, 'D34') as D34
      , sysdate as 记录日期, user as 记录人, null as 说明, a.编目日期,
       a.出院日期
  from 病案主页 a, 病人信息 b
 where a.病人id = b.病人id and 
       a.病案号 = :1 
union all
select a.病人id, a.主页id, 0 as 状态,
       (select 参数值 from hqms对接参数 where 参数名 = '机构编码') as A01,
       (select 参数值 from hqms对接参数 where 参数名 = '机构名称') as A02,
       a.病案号 as A48,
       a.主页id as A49,
       To_Char(a.入院日期, 'yyyy-MM-dd HH24:mm:ss') as B12,
       To_Char(a.出院日期, 'yyyy-MM-dd HH24:mm:ss') as B15,
       '-' as A47,
       zl_fun_hqms编码对应('RC032', null, a.医疗付款方式) as A46C,
       substrb(a.姓名, 1, 40) as A11,
       Decode(a.性别, '男', 1, '女', '2', '未知', 0, 9) as A12C,
       To_Char(b.出生日期, 'yyyy-MM-dd') as A13,
       zl_fun_hqms_Age(a.病人id, a.主页id, a.年龄, 1) as A14,
       b.国籍 as A15C,
       zl_fun_hqms编码对应('RC002', null, a.婚姻状况) as A21C,
       zl_fun_hqms编码对应('RC003', null, a.职业) as A38C,
       zl_fun_hqms编码对应('RC035', null, b.民族) as A19C,
       Nvl(b.身份证号, '-') as A20,
         DECODE(b.出生地点,'','贵州省六盘水市钟山区',b.出生地点)  as A22,
       Nvl(zl_fun_hqms_城市(a.病人id, a.主页id, a.家庭地址), '23') as A23C,
        DECODE( a.户口地址,'','贵州省六盘水市钟山区', a.户口地址)   as A24,
       DECODE(a.户口地址邮编,'','553000',a.户口地址邮编)  as A25C,
       a.家庭地址 as A26,
         DECODE(a.家庭电话,'','-',a.家庭电话) as A27,
        DECODE(a.家庭地址邮编,'','553000',a.家庭地址邮编) as A28C,
       a.单位地址 as A29,
       DECODE(a.单位电话,'','-',a.单位电话) as A30,
       DECODE(a.单位邮编,'','-',a.单位邮编) as A31C,
     DECODE(a.联系人姓名,'',substrb(a.姓名, 1, 40),substrb(a.联系人姓名, 1, 40)) as A32,
       zl_fun_hqms编码对应('RC033', null, a.联系人关系) as A33C,
       DECODE(a.联系人地址,'','-',a.联系人地址) as A34,
      DECODE(a.联系人电话,'','-',a.联系人电话) as A35,
       zl_fun_hqms编码对应('RC026', null, a.入院方式) as B11C,
       zl_fun_hqms编码对应('RC023', a.入院科室id) as B13C,
       NVL(a.入院病床,'-' ) as B14,
       (select To_Char(wmsys.wm_concat(zl_fun_hqms编码对应('RC023', 科室id)))
           from 病人变动记录
          where 病人id = a.病人id and 主页id = a.主页id and 开始原因 = 3) as B21C,
       zl_fun_hqms编码对应('RC023', a.出院科室id) as B16C,
       decode(a.出院病床,'','-',a.出院病床) as B17,
       a.住院天数 as B20,
       zl_fun_hqms诊断(a.病人id, a.主页id, 1, 1, 1) as C01C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 1, 1, 2) as C02N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 1, 1) as C03C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 1, 2) as C04N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 1, 3) as C05C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 2, 1) as C06x01C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 2, 2) as C07x01N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 2, 3) as C08x01C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 3, 1) as C06x02C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 3, 2) as C07x02N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 3, 3) as C08x02C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 4, 1) as C06x03C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 4, 2) as C07x03N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 4, 3) as C08x03C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 5, 1) as C06x04C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 5, 2) as C07x04N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 5, 3) as C08x04C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 6, 1) as C06x05C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 6, 2) as C07x05N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 6, 3) as C08x05C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 7, 1) as C06x06C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 7, 2) as C07x06N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 7, 3) as C08x06C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 8, 1) as C06x07C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 8, 2) as C07x07N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 8, 3) as C08x07C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 9, 1) as C06x08C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 9, 2) as C07x08N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 9, 3) as C08x08C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 10, 1) as C06x09C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 10, 2) as C07x09N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 10, 3) as C08x09C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 11, 1) as C06x10C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 11, 2) as C07x10N,
       zl_fun_hqms诊断(a.病人id, a.主页id, 3, 11, 3) as C08x10C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 6, 1, 1) as C09C,
       zl_fun_hqms诊断(a.病人id, a.主页id, 6, 1, 2) as C10N,
       Nvl(zl_fun_病案主页从表(a.病人id, a.主页id, '病理号'), '-') as C11,
       zl_fun_hqms诊断(a.病人id, a.主页id, 7, 1, 1) as C12C,   
       zl_fun_hqms诊断(a.病人id, a.主页id, 7, 1, 2) as C13N,
       (select Decode(Count(1), 0, 1, 2)
           from 病人过敏记录
          where 病人id = a.病人id and 主页id = a.主页id and nvl(结果, 0) = 1 and
                药物名 is not null) as C24C,
       (select To_Char(wmsys.wm_concat(distinct 药物名))
           from 病人过敏记录
          where 病人id = a.病人id and 主页id = a.主页id and nvl(结果, 0) = 1 and
                药物名 is not null) as C25,
      Nvl(zl_fun_病案主页从表(a.病人id, a.主页id, '科主任'), '郭炯辉') as B22,
      Nvl(zl_fun_病案主页从表(a.病人id, a.主页id, '主任医师'), '郭炯辉')   as B23,
       Nvl(zl_fun_病案主页从表(a.病人id, a.主页id, '主治医师'), '郭炯辉')  as B24,
       a.住院医师 as B25,
       Nvl(a.责任护士, '李美星')   as B26,
       zl_fun_病案主页从表(a.病人id, a.主页id, '进修医师') as B27,
       zl_fun_病案主页从表(a.病人id, a.主页id, '实习医师') as B28,
       a.编目员姓名 as B29,
       decode(zl_fun_病案主页从表(a.病人id, a.主页id, '病案质量'), '甲', 1,
               '乙', 2, '丙', 3, 1) as B30C,
       zl_fun_病案主页从表(a.病人id, a.主页id, '质控医师') as B31,
       zl_fun_病案主页从表(a.病人id, a.主页id, '质控护士') as B32,
       zl_fun_病案主页从表(a.病人id, a.主页id, '主页质量日期') as B33,
       Decode(a.尸检标志, 1, 1, 2) as C34C,
       decode(a.血型, 'A型', 1, 'B型', 2, 'O型', 3, 'AB型', 4, '不详', 5,
               '未查', 6, 5) as C26C,
       decode(zl_fun_病案主页从表(a.病人id, a.主页id, 'RH'), '阴', 1, '阳',
               2, '不详', 3, '未查', 4, 3) as C27C,
       NVL(zl_fun_hqms手术(a.病人id, a.主页id, 1, 1),'-') as C14x01C,
       nvl(zl_fun_hqms手术(a.病人id, a.主页id, 1, 2),'-') as C15x01N,
       nvl(zl_fun_hqms手术(a.病人id, a.主页id, 1, 3),'-') as C16x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 4) as C17x01,
       
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 5) as C18x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 6) as C19x01,
     
       Nvl( zl_fun_hqms手术(a.病人id, a.主页id, 1, 7), zl_fun_hqms手术(a.病人id, a.主页id, 1, 6))  as C20x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 8) as C21x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 9) as C22x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 1, 10) as C23x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 1) as C35x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 2) as C36x01N,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 3) as C37x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 4) as C38x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 5) as C39x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 6) as C40x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 7) as C41x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 8) as C42x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 9) as C43x01C,
       zl_fun_hqms手术(a.病人id, a.主页id, 2, 10) as C44x01,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 1) as C35x02C,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 2) as C36x02N,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 3) as C37x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 4) as C38x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 5) as C39x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 6) as C40x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 7) as C41x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 8) as C42x02C,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 9) as C43x02C,
       zl_fun_hqms手术(a.病人id, a.主页id, 3, 10) as C44x02,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 1) as C35x03C,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 2) as C36x03N,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 3) as C37x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 4) as C38x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 5) as C39x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 6) as C40x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 7) as C41x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 8) as C42x03C,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 9) as C43x03C,
       zl_fun_hqms手术(a.病人id, a.主页id, 4, 10) as C44x03,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 1) as C35x04C,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 2) as C36x04N,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 3) as C37x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 4) as C38x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 5) as C39x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 6) as C40x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 7) as C41x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 8) as C42x04C,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 9) as C43x04C,
       zl_fun_hqms手术(a.病人id, a.主页id, 5, 10) as C44x04,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 1) as C35x05C,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 2) as C36x05N,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 3) as C37x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 4) as C38x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 5) as C39x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 6) as C40x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 7) as C41x05,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 8) as C42x05C,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 9) as C43x05C,
       zl_fun_hqms手术(a.病人id, a.主页id, 6, 10) as C44x05,
      decode(zl_fun_hqms_Age(a.病人id, a.主页id, a.年龄, 2),'0','',zl_fun_hqms_Age(a.病人id, a.主页id, a.年龄, 2)) as A16,
       zl_fun_病案主页从表(a.病人id, a.主页id, '新生儿出生体重') as A18x01,
       Null as A18x02,
       Null as A18x03,
       Null as A18x04,
       Null as A18x05,
       zl_fun_病案主页从表(a.病人id, a.主页id, '新生儿入院体重') as A17,
        nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)), 1,instr(max(decode(信息名, '昏迷时间', 信息值)), ',') - 1) as 昏迷时间
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C28,
        nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',') + 1,
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               instr(max(decode(信息名, '昏迷时间', 信息值)), ',') + 1) -
                         instr(max(decode(信息名, '昏迷时间', 信息值)), ',') - 1)
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C29,
       nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               instr(max(decode(信息名, '昏迷时间', 信息值)), ',') + 1) + 1,
                        instr(max(decode(信息名, '昏迷时间', 信息值)), '|') -
                         (instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                                instr(max(decode(信息名, '昏迷时间', 信息值)), ',') + 1) + 1))
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C30,
       nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), '|') + 1,
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               (instr(max(decode(信息名, '昏迷时间', 信息值)), '|')) + 1) -
                         instr(max(decode(信息名, '昏迷时间', 信息值)), '|') - 1)
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C31,
       nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               (instr(max(decode(信息名, '昏迷时间', 信息值)), '|')) + 1) + 1,
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                                      (instr(max(decode(信息名, '昏迷时间', 信息值)),
                                              '|')) + 1) + 1) -
                         instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               (instr(max(decode(信息名, '昏迷时间', 信息值)), '|')) + 1) - 1)
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C32,
       nvl((select substr(max(decode(信息名, '昏迷时间', 信息值)),
                        instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                               instr(max(decode(信息名, '昏迷时间', 信息值)), ',',
                                      (instr(max(decode(信息名, '昏迷时间', 信息值)),
                                              '|')) + 1) + 1) + 1)
           from 病案主页从表
          where 病人id = a.病人id and 主页id = a.主页id),'0') as C33,
       Decode(zl_fun_病案主页从表(a.病人id, a.主页id, '31天内再住院'), Null,
               1, '', 1, 2) as B36C,
       zl_fun_病案主页从表(a.病人id, a.主页id, '31天内再住院') as B37,
       decode(a.出院方式, '医嘱离院', 1, '转院', 2, '转社区', 3, '正常', 1,
               '自动出院', 1, '其他', 9, '非医嘱离院', 4, '死亡', 5,
               '回常驻地', 9, 9) as B34C,
       zl_fun_病案主页从表(a.病人id, a.主页id, '出院转入') as B35,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D01') as D01,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D09') as D09,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D11') as D11,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D12') as D12,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D13') as D13,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D14') as D14,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D15') as D15,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D16') as D16,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D17') as D17,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D18') as D18,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D19') as D19,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D19x01') as D19x01,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D20') as D20,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D20x01') as D20x01,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D20x02') as D20x02,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D21') as D21,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D22') as D22,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D23') as D23,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D23x01') as D23x01,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D24') as D24,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D25') as D25,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D26') as D26,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D27') as D27,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D28') as D28,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D29') as D29,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D30') as D30,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D31') as D31,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D32') as D32,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D33') as D33,
       zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D34') as D34
      , sysdate as 记录日期, user as 记录人, null as 说明, a.编目日期,
       a.出院日期
  from 病案主页 a, 病人信息 b
 where a.病人id = b.病人id and 
       a.病案号 = :2
       AND zlhqms.zl_fun_hqms费用test(a.病人id, a.主页id, 'D01')<>0'''