# Generated by Django 3.0.3 on 2020-03-05 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '设备类别',
                'verbose_name_plural': '设备类别',
                'db_table': 'hisx_DeviceCategorys',
            },
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sn', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(default=1)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('mac', models.CharField(blank=True, max_length=100, null=True)),
                ('installdate', models.DateField(auto_now_add=True)),
                ('runos', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
                'db_table': 'hisx_DeviceInfos',
            },
        ),
        migrations.CreateModel(
            name='InstallLocation',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '安装位置',
                'verbose_name_plural': '安装位置',
                'db_table': 'hisx_InstallLocations',
            },
        ),
        migrations.CreateModel(
            name='devicetopo',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=50)),
                ('x', models.IntegerField(default=1)),
                ('y', models.IntegerField(default=1)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informationdevice.DeviceInfo')),
            ],
            options={
                'verbose_name': '设备拓扑',
                'verbose_name_plural': '设备拓扑',
                'db_table': 'hisx_Equtopo',
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('devicectegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informationdevice.DeviceCategory', verbose_name='类别')),
            ],
            options={
                'verbose_name': '设备型号',
                'verbose_name_plural': '设备型号',
                'db_table': 'hisx_DeviceModels',
            },
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='devicemodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informationdevice.DeviceModel'),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='installlocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informationdevice.InstallLocation'),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informationdevice.DeviceInfo'),
        ),
    ]
